# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_auto_20180112_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplebasket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='product.price'),
        ),
    ]
