# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_auto_20180112_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplebasket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.Product'), max_digits=6),
        ),
    ]
