# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_auto_20180112_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplebasket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
