# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('BG', 'BIG')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredient',
            field=models.ManyToManyField(db_column=models.CharField(max_length=50), to='pizza_app.Ingredient'),
        ),
        migrations.AddField(
            model_name='pizzavariation',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.Pizza'),
        ),
    ]
